In [ ]:
import numpy as np

x = [1, 2, 0, -1, -2, 0]
h = [1, -1]
np.convolve(x, h)



array([ 1,  1, -2, -1, -1,  2,  0])

In [ ]:
x = [1, 2, 0, -1, -2, 0]
h = [1, 2, 1]
np.convolve(x, h)

array([ 1,  4,  5,  1, -4, -5, -2,  0])

In [7]:
x = [1, 2, 0, -1, -2, 0]
h = [1, -2, 1]
np.convolve(x, h)

array([ 1,  0, -3,  1,  0,  3, -2,  0])