# Python Fundamentals I

### MPATE-GE 2598 Fundamentals of Digital Signal Theory Lab

Adapted from [Introduction to Data Science with Python](https://nustat.github.io/DataScience_Intro_python/Introduction%20to%20Python%20and%20Jupyter%20Notebooks.html) by Northwestern University's Department of Statistics and Data Science.

## More on Variables and Data Types

We can see all of the variables that exist in our current notebook session by running the `IPython` command `whos`. It will also show us useful information about each variable.

In [1]:
today = "Tuesday"
temperature = 32.1
is_january = True
is_dst = True

In [2]:
whos

Variable      Type     Data/Info
--------------------------------
is_dst        bool     True
is_january    bool     True
temperature   float    32.1
today         str      Tuesday


What happens if we restart our kernel? Try it by going to `Kernel` > `Restart Kernel`.

In [4]:
is_dst

True

Restarting your kernel is a way of stopping or "killing" an existing Python session. This will clear your "memory" of any existing objects, so if you try to refer to an object that was cleared, you will get a `NameError`. You will have to re-execute the cell where you defined the variables in order to get it back into the session.

Strings (`str`) are a series of characters enclosed in single or double quotes (`'` or `"`) which usually represent text. There is no difference between the type of quotes you use, you just have to make sure that you are consistent (i.e., you cannot start a string with a single quote and end it with a double quote).

Strings can also be added. Pay attention to spaces!

In [5]:
first_name = "Ian"
last_name = "Zhu"

In [8]:
full_name = first_name + last_name

In [9]:
print(full_name)

IanZhu


How do we fix this?

In [10]:
# by default, it adds a space, can change this with the sep argument
print(first_name, last_name)

Ian Zhu


In [12]:
full_name = first_name + " " + last_name
print(full_name)

Ian Zhu


What if I need to combine an object with a different data type with a string?

In [15]:
year = 2026

signature = full_name + " " + year

TypeError: can only concatenate str (not "int") to str

Depending on what you are trying to do, you need to _cast_ your objects to a different data type.

In [16]:
signature = full_name + " " + str(year)
print(signature)

Ian Zhu 2026


In [17]:
type(year)

int

In [18]:
float(42)

42.0

In [19]:
int(68.9)

68

There is also this neat way of automatically casting numerical objects to strings!

In [20]:
s = f"My name is {first_name} {last_name}. We are currently in the year {year}."
print(s)

My name is Ian Zhu. We are currently in the year 2026.


## Data Structures

So far, we have been working with objects that hold a single value. What if we want to collect multiple values together?

There are several different types of data containers in base Python. We will focus on the most important ones.

The following data structures can hold data of any type.
* Lists
* Tuples
* Dictionaries (not used in this class)

In order to select a piece of data from a structure, we need to _index_ it.
Python is a zero-indexed programming language, meaning that the first item
in a structure has an index of **`0`**.

### Tuples

A tuple is a sequence of objects separated by commas, enclosed in parentheses `()`.

* Ordered
* Allow duplicate values
* Fixed length
* Cannot be changed (immutable)

In [21]:
lotto_num = (57, 12, 49, 36, 13, 40)

In [22]:
# positive indexing
lotto_num[1]

12

In [23]:
# negative indexing
lotto_num[-1]

40

In [25]:
# tuples are immutable so if you try to change one of the values you will get an error!
lotto_num[4] = 19

TypeError: 'tuple' object does not support item assignment

### Lists

A list is a sequence of objects separated by commas, enclosed in square brackets `[]`.

* Ordered
* Allow duplicate values
* Variable length
* Can be changed (mutable)

In [27]:
fruits = ['apple', 'banana', 'pear', 'grape', 'cherry', 'orange']

In [28]:
# we can index lists similarly to tuples
fruits[0]

'apple'

In [30]:
# what happens if we use an index that is too high?
fruits[11]

IndexError: list index out of range

In [32]:
# we can find the number of items in a list
len(fruits)

6

Selecting a portion of a list (and some other data structures) is known as _slicing_.
It creates a new list with elements from the _start_ (inclusive) and _stop_ (exclusive) values.

In [34]:
# we can select multiple items from a list
fruits[2:5]

['pear', 'grape', 'cherry']

In [37]:
# we can add to the list
fruits.append('kiwi')
fruits

['apple', 'banana', 'pear', 'grape', 'cherry', 'orange', 'kiwi', 'kiwi']

In [38]:
# we can modify the list
fruits[0] = 'honeycrisp apple'
fruits

['honeycrisp apple',
 'banana',
 'pear',
 'grape',
 'cherry',
 'orange',
 'kiwi',
 'kiwi']

In [39]:
# we can also combine lists
veggies = ['onion', 'carrot', 'spinach', 'broccoli']
produce = fruits + veggies
produce

['honeycrisp apple',
 'banana',
 'pear',
 'grape',
 'cherry',
 'orange',
 'kiwi',
 'kiwi',
 'onion',
 'carrot',
 'spinach',
 'broccoli']

You can even make a list of lists. This is called a _nested_ list.

In [41]:
matrix = [[9, 1, 4], [5, 2, 8], [2, 8, 6]]

In [42]:
# the first item in the list is itself a list
matrix[0]

[9, 1, 4]

In [43]:
# we can index twice to get a specific value
matrix[0][1]

1

In [44]:
# we can still change one of the numbers
matrix[1][2] = 3
matrix

[[9, 1, 4], [5, 2, 3], [2, 8, 6]]

## Built-In Functions

The main function we have used up to this point is the `print()` function.
It is built-in to what we call base Python.
There are several other built-in functions that we can use.

In [45]:
# add elements of a list
x = [2, 3, 5]
sum(x)

10

In [46]:
# get the absolute value of a number
abs(-6)

6

In Jupyter, there is an easy way to check what kind of input a function is expecting.
Type the name of the function and then use `Shift` + `Tab`.

Let's take a look at the `range` function. You will end up using this function a lot, especially with loops!

In [49]:
# sequence from 0 through 9
range(10)

range(0, 10)

In [ ]:
# sequence from 10 through 19
range(10, 20)

In [52]:
# every other number from 0 to 20
range(0, 20, 2)

range(0, 20, 2)

In [53]:
# ignore the for loop for now, this is just to show the sequence
for i in range(0, 20, 2):
    print(i)

0
2
4
6
8
10
12
14
16
18


## Libraries

Up to this point, everything we have done has been in base Python.
What if we want to use a function or object that someone else built?

In that case, we need to import these external _libraries_ or _packages_.

First, we must install them.
You can do this either from the Anaconda Navigator or from the command-line. Whichever you are more comfortable with!

For the command line, you should use either `pip install` or `conda install`.

Let's make sure you have the following packages installed:
* `numpy`
* [`librosa`](https://librosa.org/)
* `matplotlib`

Once you have them installed, you can import them into this notebook.
Note: you may have to restart your kernel if you get a `ModuleNotFoundError`.

In [57]:
# import them with their common aliases to avoid repetitive typing
!pip install numpy librosa matplotlib
import numpy as np
import librosa
import matplotlib.pyplot as plt


Matplotlib is building the font cache; this may take a moment.


### NumPy

This is one of the most important packages you will use for any sort of numerical analysis in Python.
The main data structure used by `numpy` is called an _array_ (`numpy.ndarray`).

An array is an $n$-dimensional and homogenous data structure.

You can read a great explanation of why we use NumPy arrays [here](https://nustat.github.io/DataScience_Intro_python/NumPy.html#why-do-we-need-numpy-arrays).

In [ ]:
# lets make a simple array

my_arr = np.array([[1, 2, 3], [4, 5, 6]])
my_arr

array([[1, 2, 3],
       [4, 5, 6]])

#### Basic Attributes

In [58]:
# check its object type
type(my_arr)

numpy.ndarray

In [59]:
# get its dimensionality
my_arr.ndim

2

In [61]:
# get its shape
# for 2D arrays, it's (row, column)
my_arr.shape

(2, 3)

In [62]:
# check what type of numeric data is stored
my_arr.dtype

dtype('int64')

In [63]:
# transpose
my_arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

#### Operations

In [64]:
# you can just run then ignore this if it does not make sense
# set a seed for reproducibility
np.random.seed(10)

In [65]:
# make some random arrays
arr1 = np.random.randn(3, 4)
arr2 = np.random.randn(2, 3)
arr3 = np.random.randint(0, 100, size=(3, 4))

In [66]:
print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)
print("\nArray 3:")
print(arr3)

Array 1:
[[ 1.3315865   0.71527897 -1.54540029 -0.00838385]
 [ 0.62133597 -0.72008556  0.26551159  0.10854853]
 [ 0.00429143 -0.17460021  0.43302619  1.20303737]]

Array 2:
[[-0.96506567  1.02827408  0.22863013]
 [ 0.44513761 -1.13660221  0.13513688]]

Array 3:
[[13 92 86 30]
 [30 89 12 65]
 [31 57 36 27]]


In [67]:
# addition, subtraction, division, multiplication are all element-wise
arr1 + arr3

array([[14.3315865 , 92.71527897, 84.45459971, 29.99161615],
       [30.62133597, 88.27991444, 12.26551159, 65.10854853],
       [31.00429143, 56.82539979, 36.43302619, 28.20303737]])

In [69]:
# array shapes must match or else you will get an error
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (3,4) (2,3) 

In [70]:
# we can also apply the same scalar operation to each element
arr2 / 2

array([[-0.48253284,  0.51413704,  0.11431507],
       [ 0.22256881, -0.56830111,  0.06756844]])

In [73]:
# matrix multiplication is NOT the same as element-wise multiplication
np.matmul(arr2, arr1)

array([[-0.6451836 , -1.47065537,  1.86343428,  0.39475919],
       [-0.11289267,  1.11325349, -0.93117904,  0.03546625]])

#### Useful NumPy Functions

In [75]:
# evenly spaced numbers in an interval
# quantity is specified (default 50)
np.linspace(0, 5, num=15)

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

In [76]:
# evenly spaced numbers in an interval
# distance between numbers is specified (default 1)
np.arange(5, 12, step=0.75)

array([ 5.  ,  5.75,  6.5 ,  7.25,  8.  ,  8.75,  9.5 , 10.25, 11.  ,
       11.75])

In [77]:
# max
np.max(arr3)

np.int64(92)

In [78]:
# min
np.min(arr3)

np.int64(12)

In [79]:
# absolute value
np.abs(arr1)

array([[1.3315865 , 0.71527897, 1.54540029, 0.00838385],
       [0.62133597, 0.72008556, 0.26551159, 0.10854853],
       [0.00429143, 0.17460021, 0.43302619, 1.20303737]])

In [82]:
arr2

array([[-0.96506567,  1.02827408,  0.22863013],
       [ 0.44513761, -1.13660221,  0.13513688]])

In [81]:
# average across entire array
np.mean(arr2)

np.float64(-0.044081530493576736)

In [85]:
arr2.shape

(2, 3)

In [84]:
# average across a specific dimension
np.mean(arr2, axis=0)  # average across rows

array([-0.25996403, -0.05416407,  0.1818835 ])

## User-Defined Functions

A _function_ is very similar to the kind of function you learned about in your early math classes.
It takes an input, performs some sort of operation, and gives you an output.

The annoying $y=mx+b$ equation is a function.
It takes a value for $x$, multiplies it by the slope $m$, and adds the $y$-intercept $b$.
This gives you a value for $y$.

We can implement this in Python!

In [86]:
# y = 2x + 1
m = 2
b = 1

x = 4

In [87]:

y = m * x + b
print(f"If x = {x}, then y = {y}") 

If x = 4, then y = 9


Now, let's say that I want to find out what $y$ is if $x = -1$.

I have re-assign `x` and re-write the equation. This becomes even more annoying if I want to change the slope or intercept!

In [88]:

x = -1
y = m * x + b
print(f"If x = {x}, then y = {y}") 

If x = -1, then y = -1


To avoid copying and pasting lines of code over and over again, we can define our own _function_!

There is a very specific structure that you need to follow.

```
def function_name(arg1, arg2, ...):
    body of statements
    return
```
If there is one quirk about Python, it is that **indentation matters**. This white space helps to structure the code and make it more easily readable. If you do not properly indent, you will get an `IndentationError`.

An indentation is equivalent to 4 spaces or one `Tab`.

In [1]:
# I can turn my linear equation into a function
def line(x, m, b):
    y = m * x + b
    return y

In [3]:
# I can call my function after defining it
line(-1, 2, 1)

-1

In [4]:
# I can easily change my parameters
line(-1, 3, 0)

-3

What if I want my function to use some default values for certain arguments or parameters? 

Then, you can set the default value in the definition of the function. This parameter then becomes _optional_. When you call the function, if you do not explicitly provide a parameter, it will use the default one.

In [5]:
def line(x, m=1, b=0):
    y = m * x + b
    return y

In [6]:
# y = x
line(1)

1

In [10]:
# y = x + 5
line(1, 5)

5

In [11]:
# y = 0.5x
# if you do not use the name of the argument, Python will guess what you are referring to by position
line(1, 0.5)

0.5

Sometimes, your function may not have any input and/or output.
That's ok! You still need to use the parentheses `()` to call it.

In [12]:
def hello_world():
    print("hello world!")
    print("that is all there is to say")

In [13]:
hello_world()

hello world!
that is all there is to say


In [97]:
# if you do not have the () it just returns the function as an object
line(1, 0.5)

0.5

### Global vs. Local Variable Scope

It is extremely important to understand that variables you define in your function, only exist _within_ your function.

If you try to access this variable outside of your function definition, you will either get an error (`NameError`) or be referring to the wrong variable!

These variables definied in your function are _local_ to your function, while the ones you define outside in your environment are _global_.

In [14]:
# this is global
borough = "Manhattan"

In [15]:
def bagel(flavor, schmear, topping):
    order = f"Gimme a {flavor} bagel with {schmear} and {topping}"
    return order

In [16]:
breakfast = bagel("blueberry", "butter", "pickles")

In [17]:
print(breakfast, "in", borough)

Gimme a blueberry bagel with butter and pickles in Manhattan


In [18]:
# this local variable is only accessible from within the bagel function!
order

NameError: name 'order' is not defined

## Conditionals

This is where programming starts to become powerful.
Using conditional statements, you can tell the computer what to do depending on whether a certain statement is true or not (remember booleans?).
```
if condition:
    statement
```
There are also different conditions and boolean operators which are useful in `if` statements.
* `a == b`: check for equality between `a` and `b`
* `a < b`: check if `a` is less than `b`
* `a <= b`: check if `a` is less than or equal to `b`
* `a > b`: check if `a` is greater than `b`
* `a >= b`: check if `a` is greater than or equal to `b`
* `a != b`: check if `a` is *not* equal to `b`
* `c and d`: both conditions must be `True`
* `c or d`: at least one condition must be `True`
* `not c`: the condition must be not `True` (so `False`)
* `f in e`: check if `f` is contained in `e` (usually a list)

In [ ]:
# check if a number is negative

x = -45

if x < 0:
    print(f"{x} is negative")
else:
    print(f"{x} is non-negative")

x is negative


If we want the computer to something different when the condition is `False`, we can add the `else` clause.
```
if condition:
    statement1
else:
    statement2
```

In [20]:
x = 3

if x < 0:
    print(f"{x} is a negative number")
else:
    print(f"{x} is a non-negative number")

3 is a non-negative number


If we have multiple conditions we want to check, then we can use `elif`
```
if condition1:
    statement1
elif condition2:
    statement2
else:
    statement3
```

In [21]:
x = 29

if x < 0:
    print(f"{x} is a negative number")
elif x > 0:
    print(f"{x} is a positive number")
else:
    print(f"{x} is neither a positive nor negative number")

29 is a positive number


## Loops

Loops allow you to run certain lines of code multiple times.
There are two types of loops in Python: `while` loops and `for` loops.

### `while` Loops

In a `while` loop, the statements in the block will be executed repeatedly as long at the condition is `True`.
```
while condition:
    statement(s)
```
With these kinds of loops, you need to be careful to make sure that eventually the loop is broken.
This is usually done by making changes within the loop so that eventually the condition will be `False`.
If you do not do this, you will get an _infinite_ loop!

In [22]:
i = 0

while i < 10:
    print(i)
    i += 1

0
1
2
3
4
5
6
7
8
9


### `for` Loops

In a `for` loop, you _iterate_ over a finite sequence (e.g., list, ranges, etc.).
The statement(s) in the loop is executed once for each item in the sequence.
```
for value in sequence:
    statement(s)
```

In [23]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


## Class Exercise

Define a function called `unique_list` which accepts a list of numbers and returns a list of unique elements from that list. You may assume that the user is using a valid input.

In [30]:
def unique_list(lst):
    output = []
    # for i in range(len(lst)):
    #     if lst[i] not in lst[:i]:
    #         output.append(lst[i])
    # return output
    for i in lst:
        if i not in output:
            output.append(i)
    return output

In [31]:
# use this list to check your function
x = [34, 8, 4, 90, 4, 13, 13, 8, 27, 4]
unique_list(x)

[34, 8, 4, 90, 13, 27]

***
There was a lot of information today, but we actually only looked at these programming fundamentals at a high level. I strongly recommend that you take a look at the Python resources in the syllabus for more detailed explanations about functions, conditionals, loops, etc. to reinforce what was covered in this notebook.

Next time, we will start working with audio!

_End of Class 2_